apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-agent-1
  namespace: a2a-demo # æ›´æ–°ï¼šä½¿ç”¨ a2a-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote-agent-1
  template:
    metadata:
      labels:
        app: remote-agent-1
    spec:
      containers:
      - name: remote-agent-1-container
        image: 182399696164.dkr.ecr.ap-southeast-1.amazonaws.com/image/a2a_demo_remote_agent1:20251010052359 # ğŸš¨ æ›¿æ›æˆä½ çš„ Docker image è·¯å¾‘
        ports:
        - containerPort: 50001