apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-agent-2
  namespace: a2a-demo # æ›´æ–°ï¼šä½¿ç”¨ a2a-demo
  labels:
    agentRole: train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote-agent-2
  template:
    metadata:
      labels:
        app: remote-agent-2
        agentRole: train
    spec:
      serviceAccountName: ds-a2a-remote-agent-b-sa  # ä½¿ç”¨ IRSA Service Account
      containers:
      - name: remote-agent-2-container
        image: 182399696164.dkr.ecr.ap-southeast-1.amazonaws.com/image/a2a_demo_remote_agent2:20251010052359 # ğŸš¨ æ›¿æ›æˆä½ çš„ Docker image è·¯å¾‘
        ports:
        - containerPort: 50002
        env:
        - name: LLM_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: agent-llm-config
              key: REMOTE2_MODEL_PROVIDER
        - name: LLM_MODEL_ID
          valueFrom:
            configMapKeyRef:
              name: agent-llm-config
              key: REMOTE2_MODEL_ID
        - name: METRICS_ENABLED
          value: "true"

